services:
  nodecompose:
    build: 
      context: .
      # where we want all this files and folders for this image to pulled from 
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app