name: CI - NodeCloudOps

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image for testing
        run: docker build -t ghcr.io/keshavdesai24/nodecloudops-test -f Dockerfile.dev .

      - name: Run tests inside Docker container
        run: docker run --rm ghcr.io/keshavdesai24/nodecloudops-test npm test
